# Generated by Django 4.1.2 on 2022-11-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='GameType',
        ),
    ]
