# Generated by Django 4.1.2 on 2022-11-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_rename_type_gametype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, through='levelupapi.GamerEvent', to='levelupapi.event'),
        ),
    ]
