# Generated by Django 4.1.2 on 2022-11-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_alter_gamer_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='gamers',
            field=models.ManyToManyField(blank=True, through='levelupapi.GamerEvent', to='levelupapi.gamer'),
        ),
    ]
